---
# tasks file for lameapp

- name: checkout lameapp
  git: repo=https://github.com/jsmartin/lameapp.git
       dest=/var/www/lameapp
       version={{ lameapp_version }}

- name: set permissions on app
  file: name=/var/www/lameapp/lame.py mode=0755

- name: add apache config file
  copy: src=lameapp.conf dest={{ sites_available }}
  notify: restart apache

- name: link app config
  file: src={{ sites_available }}/lameapp.conf dest={{ sites_enabled}}/lameapp.conf state=link

- meta: flush_handlers

- name: check for proper response
  uri: url=http://localhost/lame return_content=yes
  register: result
  until: '"Hello Moon" in result.content'
  retries: 10
  delay: 1
