---
- hosts: web
  name: This is a play within a playbook
  become: yes

  vars:
    httpd_packages:
    - httpd
    - mod_wsgi
    apache_test_message: This is a test message
    apache_max_keep_alive_requests: 115

  tasks:

  - name: install libselinux-python
    yum:
      name: libselinux-python
      state: present
    tags: package

  - name: install httpd packages
    yum: 
      name: "{{ item }}" 
      state: latest
    with_items: httpd_packages
    notify: restart apache service
    tags: package

  - name: create sites-enabled dir
    file:
      state: directory
      path: /etc/httpd/conf/sites-enabled/

  - name: copy httpd.conf
    template: 
      src: httpd.conf.j2 
      dest: /etc/httpd/conf/httpd.conf
    notify: restart apache service
    tags: config

  - name: copy index.html
    template: 
      src: index.html.j2 
      dest: /var/www/html/index.html

  - name: stop firewalld
    service: 
      name: firewalld 
      state: stopped

  handlers:
  - name: restart apache service
    service: 
      name: httpd 
      state: restarted 
      enabled: yes
