---
- hosts: web
  name: Configures apache on all the app servers
  sudo: yes

  roles:
  - apache 
  tasks:
  - name: gather apache version
    shell: "{{ apache_service }} -v|grep version|awk '{print $3}'|cut -f2 -d'/'"
    register: result

  - name: set a fact for the apache version
    set_fact: apache_version="{{ result.stdout }}"

  - name: create dynamic group with apache version
    group_by: key=apache_{{ apache_version }}

- hosts: apache_2.2.15
  name: Do this on apache 2.2.15 machines
  sudo: yes
  tasks:
  - service: name={{ apache_service }} state=restarted

- hosts: apache_2.2.22
  name: Do this on apache 2.2.22 machines
  tasks:
  - command: service {{ apache_service }} status
